---
apiVersion: v1
kind: Service
metadata:
   name: mysvc
spec:
  type: LoadBalancer/ClusterIp/NodePort
  selector:
    app: swiggy
  ports:
    - port: 80
      targetPort: 80
      

ClusterIp--means we can able to access with in the server it self
Nodeport---we can access from internet as well.we can able to specify node port if needed
Loadbalance--we cann access from multiple servers also from internet
      
